### ISSUE TITLE
update task sql builder

### ISSUE THREAD

**Issue by h1alexbel** [cqqqt/Task-Viewer-Backend#70]
the current version of task update is not flexible enough:
https://github.com/cqqqt/Task-Viewer-Backend/blob/931959876d7b2381a8fea4f416709941d286c92c/src/main/java/com/taskviewer/api/postgres/PgTasks.java#L101-L108

**Comment by cichan02** [comment]
This's the last one.

**Comment by cichan02** [comment]
I mean that I need to start doing Istio homework.

**Comment by h1alexbel** [comment]
@cichan02 OK
